/* Write your T-SQL query statement below */
  SELECT DISTINCT EMP.EMPLOYEE_ID,
        COALESCE(DEP.DEPARTMENT_ID, EMP.DEPARTMENT_ID) AS DEPARTMENT_ID
FROM EMPLOYEE AS EMP
LEFT JOIN EMPLOYEE AS DEP
ON EMP.EMPLOYEE_ID = DEP.EMPLOYEE_ID AND DEP.PRIMARY_FLAG = 'Y'